const liflyTestThemePackageJson = <String, dynamic>{
  'manifest': <String, dynamic>{
    'theme_id': 'lifly.test.mint',
    'version': '1.0.0',
    'display_name': 'Mint Test',
    'description': 'A lightweight declarative fixture for the theme runtime.',
    'author': 'Lifly Team',
    'minimum_app_version': '0.8.0',
    'supported_platforms': <String>['web', 'phone', 'desktop'],
    'supported_color_modes': <String>['light', 'dark'],
    'performance_class': 'standard',
    'assets': <Map<String, dynamic>>[
      <String, dynamic>{
        'id': 'mint-accent-icon',
        'path': 'assets/mint/accent.svg',
        'kind': 'icon',
        'required': false,
        'maximum_bytes': 4096,
        'sha256':
            '1111111111111111111111111111111111111111111111111111111111111111',
      },
    ],
    'fallback_theme_id': 'lifly.core',
    'entitlement_type': 'free',
    'platform_overrides': <String, dynamic>{
      'web': <String, dynamic>{
        'layout_variant': 'dashboard',
        'visual_density_adjustment': -0.5,
        'minimum_interactive_dimension': 40,
        'focus_ring_width': 2,
        'hover_enabled': true,
        'keyboard_navigation': true,
      },
      'phone': <String, dynamic>{
        'layout_variant': 'balanced',
        'visual_density_adjustment': 0,
        'minimum_interactive_dimension': 44,
        'focus_ring_width': 2,
        'hover_enabled': false,
        'keyboard_navigation': false,
      },
      'desktop': <String, dynamic>{
        'layout_variant': 'compact',
        'visual_density_adjustment': -1,
        'minimum_interactive_dimension': 40,
        'focus_ring_width': 2,
        'hover_enabled': true,
        'keyboard_navigation': true,
      },
    },
    'integrity': <String, dynamic>{
      'algorithm': 'sha256',
      'digest':
          '2222222222222222222222222222222222222222222222222222222222222222',
      'signer': 'lifly.official',
      'signature': 'fixture-signature-not-for-production',
    },
  },
  'tokens': <String, dynamic>{
    'light': <String, dynamic>{
      'colors': <String, dynamic>{
        'primary': '#176B52',
        'on_primary': '#FFFFFF',
        'secondary': '#496457',
        'surface': '#F7FCF8',
        'on_surface': '#17201B',
        'critical': '#BA1A1A',
        'warning': '#835500',
        'success': '#216E39',
        'info': '#00639B',
        'neutral': '#59615C',
      },
      'typography': <String, dynamic>{
        'font_family': null,
        'title_scale': 1.0,
        'body_scale': 1.0,
        'label_scale': 1.0,
      },
      'spacing': <String, dynamic>{'page': 20, 'card': 16, 'inline': 8},
      'radius': <String, dynamic>{'card': 14, 'control': 10},
      'elevation': <String, dynamic>{'card': 1},
      'density': <String, dynamic>{'visual': 0},
      'motion': <String, dynamic>{
        'enabled': true,
        'fast_ms': 110,
        'normal_ms': 180,
      },
    },
    'dark': <String, dynamic>{
      'colors': <String, dynamic>{
        'primary': '#8DD8BC',
        'on_primary': '#003829',
        'secondary': '#B0CCBC',
        'surface': '#101512',
        'on_surface': '#DFE8E1',
        'critical': '#FFB4AB',
        'warning': '#FFBA68',
        'success': '#8DDAA5',
        'info': '#92CCFF',
        'neutral': '#BEC9C1',
      },
      'typography': <String, dynamic>{
        'font_family': null,
        'title_scale': 1.0,
        'body_scale': 1.0,
        'label_scale': 1.0,
      },
      'spacing': <String, dynamic>{'page': 20, 'card': 16, 'inline': 8},
      'radius': <String, dynamic>{'card': 14, 'control': 10},
      'elevation': <String, dynamic>{'card': 1},
      'density': <String, dynamic>{'visual': 0},
      'motion': <String, dynamic>{
        'enabled': true,
        'fast_ms': 110,
        'normal_ms': 180,
      },
    },
  },
};
